name = "zillow-mcp-server"
main = "src/server/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
BASE_URL = "https://zillow-mcp-server.reed-b9b.workers.dev"

